siteTitle = "飽き性の活動記録"

siteSubTitle = "色々なことに手を出しすぎて「今まで何してきたんだっけ」ってなるので。"

siteAuthor = "hennin"

linkPrefix = "/localhost"

twitterId = "AS_predri"
githubId = "henninltn"

[[tags]]
  name = "JavaScript"
[[tags]]
  name = "ES6"
[[tags]]
  name = "React"
[[tags]]
  name = "Lisp"
[[tags]]
  name = "CommonLisp"
[[tags]]
  name = "ShellScript"
[[tags]]
  name = "ReactNative"
[[tags]]
  name = "Three.js"
[[tags]]
  name = "Python3"
[[tags]]
  name = "VCS"
[[tags]]
  name = "Git"
[[tags]]
  name = "Mercurial"

